### ISSUE TITLE
Unfinished sentence combined with another unfinished sentence.

### ISSUE THREAD

**Issue by DRyanMiller** [learn-co-curriculum/dsc-ridge-and-lasso-regression#1]
The following sentence appears under the heading 'Penalized Estimation':

"Now, instead of completely "deleting" certain predictors from a model (which is equal to setting coefficients equal to zero), wouldn't it be interesting // so-called penalized estimation operates in a way where parameter shrinkage effects are used to make some or all of the coefficients smaller in magnitude, closer to zero.'

I have inserted '//' to indicate where the two incomplete sentences are combined.

**Comment by fpolchow** [comment]
fixed, thanks for flagging!
