### ISSUE TITLE
equations are broken

### ISSUE THREAD

**Issue by Kaewin** [learn-co-curriculum/dsc-ridge-and-lasso-regression#4]
## Link to Canvas

https://github.com/learn-co-curriculum/dsc-ridge-and-lasso-regression

## Issue Subtype

- [x ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

## Any Additional Context?

the equations are broken

**Comment by jessepisel** [comment]
thanks for opening this issue :wave:. This is fixed with [2449f41](https://github.com/learn-co-curriculum/dsc-ridge-and-lasso-regression/commit/2449f41baf49d5255b1c8a4508f7de5f93a18b83). I am closing this issue at this time
