### ISSUE TITLE
Phase 3: Ridge and Lasso Regression Lesson:  Formula Error?

### ISSUE THREAD

**Issue by Bella3s** [learn-co-curriculum/dsc-ridge-and-lasso-regression#5]
## Link to Canvas

https://learning.flatironschool.com/courses/6223/assignments/226623?module_item_id=529510

## Issue Subtype

- [x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
$$ \sum_{i=1}^n(y_i - ((m_1x_{1i})-b)^2 + \lambda m_1^2 + (m_2x_{2i})-b)^2 + \lambda m_2^2)$$
```

### Concern

The formula is missing a parenthesis. It makes it unclear which part should be in the summation function and which part should not be summed.  Also, nowhere in the lesson is it noted what p is.  I'm guessing it is the number of parameters, but if so, the same variable should be used for both sums (k is used earlier). If it is different, then the text should note 'where p is ...'.  

Upon another look at the formula and in an attempt to work it out myself from the base formula with k=2, I don't believe this the above correct (although there is a real possibility I'm doing my math incorrectly).  See below for what I think the formula might actually be?

## (Optional) Proposed Solution

```
$$ \sum_{i=1}^n(y_i - m_1x_{1i} - m_2x_{2i} -b)^2 + \lambda m_1^2 + \lambda m_2^2)$$
```
## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [x] Saturn Cloud from Canvas

## Any Additional Context?

Let me know if I'm wrong + if so why!  I'm always happy to be wrong as long as it helps me learn :)

**Comment by bpurdy-ds** [comment]
While it does look "weird" that is the correct formula, see, e.g., [here](https://pub.towardsai.net/ridge-and-lasso-regression-51705b608fb9). Thank you for checking, this is indeed part of the learning experience.
