### ISSUE TITLE
Ridge and Lasso Regression Cost Function Formulas 

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-ridge-and-lasso-regression#6]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

### Concern

![Capture](https://github.com/user-attachments/assets/732a62d0-0c0f-40d5-a493-2ec931ccbd74)
similar issue for the Lasso regression formula (snapshot not included)

## (Optional) Proposed Solution

The correct formula seems to be the following: 

$$ \text{cost function ridge}= \sum_{i=1}^n(y_i - \hat{y})^2 = $$

$$ \sum_{i=1}^n\Big(y_i - (m_1x_{1i} + m_2x_{2i}) - b\Big)^2  + \lambda m_1^2 + \lambda m_2^2$$

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for raising this issue. We'll take a look.

**Comment by bpurdy-ds** [comment]
Updated readme files and made a note for future reference.
